# Generated by Django 3.0.5 on 2020-04-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=1024, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('text', models.TextField(max_length=1024, verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Форма',
                'verbose_name_plural': 'Форма',
            },
        ),
        migrations.CreateModel(
            name='ResponseVacancyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=1024, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone_number', models.TextField(max_length=1024, verbose_name='Ваш телефон')),
                ('age', models.TextField(max_length=1024, verbose_name='Возраст')),
                ('education', models.TextField(max_length=1024, verbose_name='Образование')),
                ('salary', models.TextField(max_length=1024, verbose_name='ЗП')),
                ('experience', models.TextField(max_length=1024, verbose_name='Опыт')),
                ('found_out', models.TextField(max_length=1024, verbose_name='Как нашел')),
            ],
            options={
                'verbose_name': 'Форма',
                'verbose_name_plural': 'Форма',
            },
        ),
    ]
